-- Up Migration
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS type VARCHAR(20) DEFAULT 'bike';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS license_plate VARCHAR(20);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vin VARCHAR(50);
