// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Document struct {
	ID         int32
	VehicleID  sql.NullInt32
	Name       string
	Type       sql.NullString
	FileUrl    string
	ExpiryDate sql.NullTime
	Notes      sql.NullString
	CreatedAt  sql.NullTime
}

type FuelLog struct {
	ID            int32
	VehicleID     sql.NullInt32
	Date          time.Time
	Odometer      int32
	Liters        string
	PricePerLiter string
	TotalCost     string
	FullTank      sql.NullBool
	Notes         sql.NullString
	CreatedAt     sql.NullTime
}

type Part struct {
	ID              int32
	ServiceRecordID sql.NullInt32
	Name            string
	PartNumber      sql.NullString
	Cost            sql.NullString
	Link            sql.NullString
	CreatedAt       sql.NullTime
}

type Reminder struct {
	ID             int32
	VehicleID      sql.NullInt32
	Title          string
	DueDate        sql.NullTime
	DueOdometer    sql.NullInt32
	IsRecurring    sql.NullBool
	IntervalKm     sql.NullInt32
	IntervalMonths sql.NullInt32
	Notes          sql.NullString
	IsCompleted    sql.NullBool
	CreatedAt      sql.NullTime
	Type           sql.NullString
}

type ServiceRecord struct {
	ID          int32
	VehicleID   sql.NullInt32
	Date        time.Time
	Odometer    int32
	Cost        string
	Notes       sql.NullString
	ServiceType sql.NullString
	CreatedAt   sql.NullTime
	DocumentUrl sql.NullString
}

type Vehicle struct {
	ID           int32
	Name         string
	Make         sql.NullString
	Model        sql.NullString
	Year         sql.NullInt32
	Type         sql.NullString
	Vin          sql.NullString
	LicensePlate sql.NullString
	ImageUrl     sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
