// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const completeReminder = `-- name: CompleteReminder :exec
UPDATE reminders SET is_completed = TRUE WHERE id = $1
`

func (q *Queries) CompleteReminder(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, completeReminder, id)
	return err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (vehicle_id, name, type, file_url, expiry_date, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vehicle_id, name, type, file_url, expiry_date, notes, created_at
`

type CreateDocumentParams struct {
	VehicleID  sql.NullInt32
	Name       string
	Type       sql.NullString
	FileUrl    string
	ExpiryDate sql.NullTime
	Notes      sql.NullString
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.VehicleID,
		arg.Name,
		arg.Type,
		arg.FileUrl,
		arg.ExpiryDate,
		arg.Notes,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Name,
		&i.Type,
		&i.FileUrl,
		&i.ExpiryDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createFuelLog = `-- name: CreateFuelLog :one
INSERT INTO fuel_logs (vehicle_id, date, odometer, liters, price_per_liter, total_cost, full_tank, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, vehicle_id, date, odometer, liters, price_per_liter, total_cost, full_tank, notes, created_at
`

type CreateFuelLogParams struct {
	VehicleID     sql.NullInt32
	Date          time.Time
	Odometer      int32
	Liters        string
	PricePerLiter string
	TotalCost     string
	FullTank      sql.NullBool
	Notes         sql.NullString
}

func (q *Queries) CreateFuelLog(ctx context.Context, arg CreateFuelLogParams) (FuelLog, error) {
	row := q.db.QueryRowContext(ctx, createFuelLog,
		arg.VehicleID,
		arg.Date,
		arg.Odometer,
		arg.Liters,
		arg.PricePerLiter,
		arg.TotalCost,
		arg.FullTank,
		arg.Notes,
	)
	var i FuelLog
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Date,
		&i.Odometer,
		&i.Liters,
		&i.PricePerLiter,
		&i.TotalCost,
		&i.FullTank,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createPart = `-- name: CreatePart :one
INSERT INTO parts (
  service_record_id, name, part_number, cost, link
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, service_record_id, name, part_number, cost, link, created_at
`

type CreatePartParams struct {
	ServiceRecordID sql.NullInt32
	Name            string
	PartNumber      sql.NullString
	Cost            sql.NullString
	Link            sql.NullString
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (Part, error) {
	row := q.db.QueryRowContext(ctx, createPart,
		arg.ServiceRecordID,
		arg.Name,
		arg.PartNumber,
		arg.Cost,
		arg.Link,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.ServiceRecordID,
		&i.Name,
		&i.PartNumber,
		&i.Cost,
		&i.Link,
		&i.CreatedAt,
	)
	return i, err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (vehicle_id, title, due_date, due_odometer, is_recurring, interval_km, interval_months, notes, type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, vehicle_id, title, due_date, due_odometer, is_recurring, interval_km, interval_months, notes, is_completed, created_at, type
`

type CreateReminderParams struct {
	VehicleID      sql.NullInt32
	Title          string
	DueDate        sql.NullTime
	DueOdometer    sql.NullInt32
	IsRecurring    sql.NullBool
	IntervalKm     sql.NullInt32
	IntervalMonths sql.NullInt32
	Notes          sql.NullString
	Type           sql.NullString
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, createReminder,
		arg.VehicleID,
		arg.Title,
		arg.DueDate,
		arg.DueOdometer,
		arg.IsRecurring,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.Notes,
		arg.Type,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Title,
		&i.DueDate,
		&i.DueOdometer,
		&i.IsRecurring,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.Notes,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const createServiceRecord = `-- name: CreateServiceRecord :one
INSERT INTO service_records (
  vehicle_id, date, odometer, cost, notes, service_type, document_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, vehicle_id, date, odometer, cost, notes, service_type, created_at, document_url
`

type CreateServiceRecordParams struct {
	VehicleID   sql.NullInt32
	Date        time.Time
	Odometer    int32
	Cost        string
	Notes       sql.NullString
	ServiceType sql.NullString
	DocumentUrl sql.NullString
}

func (q *Queries) CreateServiceRecord(ctx context.Context, arg CreateServiceRecordParams) (ServiceRecord, error) {
	row := q.db.QueryRowContext(ctx, createServiceRecord,
		arg.VehicleID,
		arg.Date,
		arg.Odometer,
		arg.Cost,
		arg.Notes,
		arg.ServiceType,
		arg.DocumentUrl,
	)
	var i ServiceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Date,
		&i.Odometer,
		&i.Cost,
		&i.Notes,
		&i.ServiceType,
		&i.CreatedAt,
		&i.DocumentUrl,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
  name, make, model, year, type, vin, license_plate, image_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, make, model, year, type, vin, license_plate, image_url, created_at, updated_at
`

type CreateVehicleParams struct {
	Name         string
	Make         sql.NullString
	Model        sql.NullString
	Year         sql.NullInt32
	Type         sql.NullString
	Vin          sql.NullString
	LicensePlate sql.NullString
	ImageUrl     sql.NullString
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, createVehicle,
		arg.Name,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Type,
		arg.Vin,
		arg.LicensePlate,
		arg.ImageUrl,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Type,
		&i.Vin,
		&i.LicensePlate,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const deleteFuelLog = `-- name: DeleteFuelLog :exec
DELETE FROM fuel_logs WHERE id = $1
`

func (q *Queries) DeleteFuelLog(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFuelLog, id)
	return err
}

const deleteServiceRecord = `-- name: DeleteServiceRecord :exec
DELETE FROM service_records WHERE id = $1
`

func (q *Queries) DeleteServiceRecord(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteServiceRecord, id)
	return err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, name, make, model, year, type, vin, license_plate, image_url, created_at, updated_at FROM vehicles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVehicle(ctx context.Context, id int32) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Type,
		&i.Vin,
		&i.LicensePlate,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleStats = `-- name: GetVehicleStats :one
SELECT
    (SELECT COALESCE(SUM(total_cost), 0.0)::float8 FROM fuel_logs WHERE fuel_logs.vehicle_id = $1) AS total_fuel_cost,
    (SELECT COALESCE(SUM(cost), 0.0)::float8 FROM service_records WHERE service_records.vehicle_id = $1) AS total_service_cost,
    (SELECT COALESCE(SUM(liters), 0.0)::float8 FROM fuel_logs WHERE fuel_logs.vehicle_id = $1) AS total_liters,
    (SELECT COUNT(*) FROM service_records WHERE service_records.vehicle_id = $1) AS total_services,
    (SELECT COUNT(*) FROM fuel_logs WHERE fuel_logs.vehicle_id = $1) AS total_fuel_logs
`

type GetVehicleStatsRow struct {
	TotalFuelCost    float64
	TotalServiceCost float64
	TotalLiters      float64
	TotalServices    int64
	TotalFuelLogs    int64
}

func (q *Queries) GetVehicleStats(ctx context.Context, vehicleID sql.NullInt32) (GetVehicleStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleStats, vehicleID)
	var i GetVehicleStatsRow
	err := row.Scan(
		&i.TotalFuelCost,
		&i.TotalServiceCost,
		&i.TotalLiters,
		&i.TotalServices,
		&i.TotalFuelLogs,
	)
	return i, err
}

const listDocumentsByVehicle = `-- name: ListDocumentsByVehicle :many
SELECT id, vehicle_id, name, type, file_url, expiry_date, notes, created_at FROM documents
WHERE vehicle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByVehicle(ctx context.Context, vehicleID sql.NullInt32) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Name,
			&i.Type,
			&i.FileUrl,
			&i.ExpiryDate,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuelLogsByVehicle = `-- name: ListFuelLogsByVehicle :many
SELECT id, vehicle_id, date, odometer, liters, price_per_liter, total_cost, full_tank, notes, created_at FROM fuel_logs
WHERE vehicle_id = $1
ORDER BY date DESC
`

func (q *Queries) ListFuelLogsByVehicle(ctx context.Context, vehicleID sql.NullInt32) ([]FuelLog, error) {
	rows, err := q.db.QueryContext(ctx, listFuelLogsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FuelLog
	for rows.Next() {
		var i FuelLog
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Date,
			&i.Odometer,
			&i.Liters,
			&i.PricePerLiter,
			&i.TotalCost,
			&i.FullTank,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsByServiceRecord = `-- name: ListPartsByServiceRecord :many
SELECT id, service_record_id, name, part_number, cost, link, created_at FROM parts
WHERE service_record_id = $1
`

func (q *Queries) ListPartsByServiceRecord(ctx context.Context, serviceRecordID sql.NullInt32) ([]Part, error) {
	rows, err := q.db.QueryContext(ctx, listPartsByServiceRecord, serviceRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Part
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.ServiceRecordID,
			&i.Name,
			&i.PartNumber,
			&i.Cost,
			&i.Link,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByVehicle = `-- name: ListRemindersByVehicle :many
SELECT id, vehicle_id, title, due_date, due_odometer, is_recurring, interval_km, interval_months, notes, is_completed, created_at, type FROM reminders
WHERE vehicle_id = $1 AND is_completed = FALSE
ORDER BY due_date ASC
`

func (q *Queries) ListRemindersByVehicle(ctx context.Context, vehicleID sql.NullInt32) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listRemindersByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Title,
			&i.DueDate,
			&i.DueOdometer,
			&i.IsRecurring,
			&i.IntervalKm,
			&i.IntervalMonths,
			&i.Notes,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRecordsByVehicle = `-- name: ListServiceRecordsByVehicle :many
SELECT id, vehicle_id, date, odometer, cost, notes, service_type, created_at, document_url FROM service_records
WHERE vehicle_id = $1
ORDER BY date DESC
`

func (q *Queries) ListServiceRecordsByVehicle(ctx context.Context, vehicleID sql.NullInt32) ([]ServiceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listServiceRecordsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceRecord
	for rows.Next() {
		var i ServiceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Date,
			&i.Odometer,
			&i.Cost,
			&i.Notes,
			&i.ServiceType,
			&i.CreatedAt,
			&i.DocumentUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, name, make, model, year, type, vin, license_plate, image_url, created_at, updated_at FROM vehicles
ORDER BY created_at DESC
`

func (q *Queries) ListVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.QueryContext(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.Type,
			&i.Vin,
			&i.LicensePlate,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFuelLog = `-- name: UpdateFuelLog :one
UPDATE fuel_logs
SET date = $2, odometer = $3, liters = $4, price_per_liter = $5, total_cost = $6, full_tank = $7, notes = $8
WHERE id = $1
RETURNING id, vehicle_id, date, odometer, liters, price_per_liter, total_cost, full_tank, notes, created_at
`

type UpdateFuelLogParams struct {
	ID            int32
	Date          time.Time
	Odometer      int32
	Liters        string
	PricePerLiter string
	TotalCost     string
	FullTank      sql.NullBool
	Notes         sql.NullString
}

func (q *Queries) UpdateFuelLog(ctx context.Context, arg UpdateFuelLogParams) (FuelLog, error) {
	row := q.db.QueryRowContext(ctx, updateFuelLog,
		arg.ID,
		arg.Date,
		arg.Odometer,
		arg.Liters,
		arg.PricePerLiter,
		arg.TotalCost,
		arg.FullTank,
		arg.Notes,
	)
	var i FuelLog
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Date,
		&i.Odometer,
		&i.Liters,
		&i.PricePerLiter,
		&i.TotalCost,
		&i.FullTank,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateReminder = `-- name: UpdateReminder :one
UPDATE reminders
SET title = $2, due_date = $3, due_odometer = $4, is_recurring = $5, interval_km = $6, interval_months = $7, notes = $8, type = $9
WHERE id = $1
RETURNING id, vehicle_id, title, due_date, due_odometer, is_recurring, interval_km, interval_months, notes, is_completed, created_at, type
`

type UpdateReminderParams struct {
	ID             int32
	Title          string
	DueDate        sql.NullTime
	DueOdometer    sql.NullInt32
	IsRecurring    sql.NullBool
	IntervalKm     sql.NullInt32
	IntervalMonths sql.NullInt32
	Notes          sql.NullString
	Type           sql.NullString
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, updateReminder,
		arg.ID,
		arg.Title,
		arg.DueDate,
		arg.DueOdometer,
		arg.IsRecurring,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.Notes,
		arg.Type,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Title,
		&i.DueDate,
		&i.DueOdometer,
		&i.IsRecurring,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.Notes,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const updateServiceRecord = `-- name: UpdateServiceRecord :one
UPDATE service_records
SET date = $2, odometer = $3, cost = $4, notes = $5, service_type = $6, document_url = $7
WHERE id = $1
RETURNING id, vehicle_id, date, odometer, cost, notes, service_type, created_at, document_url
`

type UpdateServiceRecordParams struct {
	ID          int32
	Date        time.Time
	Odometer    int32
	Cost        string
	Notes       sql.NullString
	ServiceType sql.NullString
	DocumentUrl sql.NullString
}

func (q *Queries) UpdateServiceRecord(ctx context.Context, arg UpdateServiceRecordParams) (ServiceRecord, error) {
	row := q.db.QueryRowContext(ctx, updateServiceRecord,
		arg.ID,
		arg.Date,
		arg.Odometer,
		arg.Cost,
		arg.Notes,
		arg.ServiceType,
		arg.DocumentUrl,
	)
	var i ServiceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Date,
		&i.Odometer,
		&i.Cost,
		&i.Notes,
		&i.ServiceType,
		&i.CreatedAt,
		&i.DocumentUrl,
	)
	return i, err
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET name = $2, make = $3, model = $4, year = $5, type = $6, vin = $7, license_plate = $8, image_url = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, name, make, model, year, type, vin, license_plate, image_url, created_at, updated_at
`

type UpdateVehicleParams struct {
	ID           int32
	Name         string
	Make         sql.NullString
	Model        sql.NullString
	Year         sql.NullInt32
	Type         sql.NullString
	Vin          sql.NullString
	LicensePlate sql.NullString
	ImageUrl     sql.NullString
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRowContext(ctx, updateVehicle,
		arg.ID,
		arg.Name,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Type,
		arg.Vin,
		arg.LicensePlate,
		arg.ImageUrl,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Type,
		&i.Vin,
		&i.LicensePlate,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
